# Generated by Django 3.2 on 2022-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_year',
            field=models.DateField(),
        ),
    ]
